HL7Austria/HL7-AT-FHIR-Core-R4

input/fsh/AustrianPatientExample01.fsh
Replaced references to valueSets with codeSystems
=> #21 Correction of the AustrianPatientExample

CONTRIBUTING.md
It was taken over from the STU3 Repo, links were updated
=> #19 Added Contributing.md

input/fsh/at-core-patient.fsh
Changed identifier.system to mandatory
=> #4 Changed identifier.system to mandatory

input/fsh/at-core-ext-patient-religion.fsh, input/landing_page/_index.yml
Correction of vs description for religion
=> #15 Correction of vs description for religion

README.md, input/fsh/Alias.fsh, input/fsh/at-core-address.fsh, input/fsh/at-core-cs-iso-3166-1-alpha-3.fsh, input/fsh/at-core-cs-religion.fsh, input/fsh/at-core-example-patient01.fsh, input/fsh/at-core-ext-address-additionalInformation.fsh, input/fsh/at-core-ext-patient-religion.fsh, input/fsh/at-core-patient.fsh, input/fsh/at-elga-vs-countryCodes.fsh, input/fsh/at-elga-vs-religion.fsh, input/hl7at_template/content/searchform.html, input/hl7at_template/includes/fragment-pagebegin.html, input/hl7at_template/includes/fragment-pageend.html, input/hl7at_template/layouts/layout-valueset.html, input/hl7at_template/package/package.json, input/ignoreWarnings.txt, input/includes/menu.xml, input/landing_page/_index.yml, input/pagecontent/index.md, sushi-config.yaml
=> #8 Added copyright information chapter

input/fsh/at-core-example-patient01.fsh, input/fsh/at-core-example-patient04-Full.fsh, input/fsh/at-core-example-patient05-FullElga.fsh, input/fsh/at-core-ext-patient-religion.fsh, input/fsh/at-core-patient.fsh
=> #3 change system to url instead of oid

.github/workflows/deploy.yml, input/landing_page/_index.yml
=> #25 Changed the deployment process

input/fsh/at-core-cs-iso-3166-1-alpha-3.fsh, input/fsh/at-core-cs-religion.fsh, input/fsh/at-elga-vs-countryCodes.fsh, input/fsh/at-elga-vs-religion.fsh
Creating pull request to activate github actions and test the changes.
Edit by Oliver: 
Closes: #13
=> #13 adding OID to ValueSets and CodeSystems

input/fsh/Organization-example-f001-burgers.fsh, input/fsh/at-core-address.fsh, input/fsh/at-core-ext-patient-religion.fsh
Closes #16 
NOTE: Please add your issue here if you work on the narrative sub-issues. we only merge this branch after all narratives have been updated.
Closes #45 
Closes #44
Closes #43
=> #16 Narrative Branch

README.md, input/fsh/at-core-patient.fsh, input/pagecontent/index.md
=> 16 narrative

ig.ini, input/fsh/at-core-example-patient04-Full.fsh
added the contentType according to the ticket
=> #61 Missing photo contentType

input/fsh/at-core-patient.fsh
Changed the binding of identifier.type to the new ELGA ValueSet for identifierTypeCodes
Closes #57
=> #57 IdentifierTypeCode Binding Change

ig.ini, input/ignoreWarnings.txt
=> 72 qa errors and warnings

input/fsh/at-core-example-patient01.fsh, input/fsh/at-core-example-patient04-Full.fsh, input/fsh/at-core-example-patient05-FullElga.fsh, input/fsh/at-core-example-patient06-GenderExtension.fsh, input/fsh/at-core-ext-patient-religion.fsh, input/fsh/at-core-patient.fsh
corrected the examples with religion as well
Closes #83
=> #83 Remove Fixed CodeSystem in Religion Extension

input/pagecontent/index.md
updated the index.md file to be up-to-date
Closes #88
=> #88 Narrative Updates

input/pagecontent/StructureDefinition-at-core-organization-intro.md
changed the narrative so that the profile can be applied to all organizations, not just for GDAs
Closes #93
=> #93 Organization Scope Adaption

input/fsh/at-core-ext-patient-religion.fsh
added the relevant context of use to the extension
Closes #91
=> #91 CoU for PatientReligion

input/fsh/at-core-ext-valueset-systemoid.fsh
added the relevant context of use to the extension
Closes #92
=> #92 CoU for SystemOID

input/fsh/at-core-example-organization02-multipleVPNR.fsh, input/fsh/at-core-organization.fsh
=> #95 expand cardinality of vpnr to 0..*

input/fsh/at-core-example-patient04-Full.fsh
=> #101 Fix inconsistent name and email address in HL7ATCorePatientExample04-Full

input/fsh/at-core-example-patient05-FullElga.fsh
=> #100 Fix Inconsistent name and email address in HL7ATCorePatientExample05-FullElga

input/fsh/at-core-organization.fsh
removed the wrong binding
Closes #104
=> #104 Organization IdentifierType Binding

input/pagecontent/index.md
added hint about administrative gender
Closes #107
=> #107 IndexPage Update

input/fsh/Alias.fsh, input/fsh/at-core-patient.fsh
added int. Extension and used HL7 AT datatype profile for address
Closes #105
=> #105 Patient birthPlace Extension

input/fsh/at-core-example-organization01.fsh, input/fsh/at-core-organization.fsh, input/pagecontent/StructureDefinition-at-core-organization-intro.md
including correction of examples and narrative
Closes #120
=> #120 Organization Correction of OID for KA-Nr

input/fsh/at-core-practitioner.fsh
=> #121 Practitioner VPNR cardinality change
